# Generated by Django 3.1.5 on 2021-01-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(help_text='News article headline', max_length=255, unique=True),
        ),
    ]
